test:
  adapter: postgresql
  username: postgres
  database: postgres
  host: localhost
  port: 5600
  pool: 5
  timeout: 5000
  prepared_statements: <%= ENV.fetch('PREPARED_STATEMENTS', '1') == '1' %>
  variables:
    citus.shard_count: 5
