name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.7'
        gemfile:
          - rails_6.1
        prepared_statements: [true, false]
        exclude:
          # activesupport-7.0.0 requires ruby version >= 2.7.0
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }} ${{ (matrix.prepared_statements && 'w/ prepared statements') || '' }}
    env:
       BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
       PREPARED_STATEMENTS: ${{ matrix.prepared_statements && '1' }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker-compose up -d
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          bundle exec rake spec
